FROM nvtienanh/hadoop-base:1.1.0-hadoop2.8-java8
MAINTAINER Anh Nguyen <nvtienanh@gmail.com>

RUN apt-get update -y
RUN apt-get install --fix-missing -q -y \
  ant \
  gcc \
  g++ \
  libkrb5-dev \
  default-libmysqlclient-dev \
  libsqlite3-0 \
  libc6-dev \
  libssl1.0.2 \
  libssl-dev \
  libsasl2-dev \
  libsasl2-modules-gssapi-mit \
  libsqlite3-dev \
  libtidy-dev \
  libxml2-dev \
  libxslt-dev \
  libffi-dev \
  make \
  maven \
  libldap2-dev \
  python-dev \
  python-setuptools \
  libgmp3-dev \
  libz-dev \
  git
